# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_processor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_processor.proto\x12\x0fimage_processor\"R\n\x15ImageProcessorRequest\x12%\n\x05image\x18\x01 \x01(\x0b\x32\x16.image_processor.Image\x12\x12\n\noperations\x18\x02 \x01(\t\",\n\x05Image\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\timagedata\x18\x02 \x01(\x0c\x32g\n\x0eImageProcessor\x12U\n\x11GetServerResponse\x12&.image_processor.ImageProcessorRequest\x1a\x16.image_processor.Image\"\x00\x62\x06proto3')



_IMAGEPROCESSORREQUEST = DESCRIPTOR.message_types_by_name['ImageProcessorRequest']
_IMAGE = DESCRIPTOR.message_types_by_name['Image']
ImageProcessorRequest = _reflection.GeneratedProtocolMessageType('ImageProcessorRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEPROCESSORREQUEST,
  '__module__' : 'image_processor_pb2'
  # @@protoc_insertion_point(class_scope:image_processor.ImageProcessorRequest)
  })
_sym_db.RegisterMessage(ImageProcessorRequest)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'image_processor_pb2'
  # @@protoc_insertion_point(class_scope:image_processor.Image)
  })
_sym_db.RegisterMessage(Image)

_IMAGEPROCESSOR = DESCRIPTOR.services_by_name['ImageProcessor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEPROCESSORREQUEST._serialized_start=42
  _IMAGEPROCESSORREQUEST._serialized_end=124
  _IMAGE._serialized_start=126
  _IMAGE._serialized_end=170
  _IMAGEPROCESSOR._serialized_start=172
  _IMAGEPROCESSOR._serialized_end=275
# @@protoc_insertion_point(module_scope)
